param(
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Get-AppVersion {
    $version = (& python -c "from version import __version__; print(__version__)").Trim()
    if (-not $version) {
        throw "Failed to read __version__ from version.py"
    }
    return $version
}

function Get-InnoSetupCompiler {
    $paths = @(
        "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
        "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
    )
    foreach ($path in $paths) {
        if (Test-Path $path) {
            return $path
        }
    }
    throw "Inno Setup 6 not found. Install from https://jrsoftware.org/isdl.php"
}

$version = Get-AppVersion
$appName = "ChatList"
$appVersionedName = "${appName}-${version}"
$exePath = Join-Path "dist" "$appVersionedName.exe"
$installerPath = Join-Path "dist" "${appVersionedName}-setup.exe"
$versionIssPath = Join-Path $PSScriptRoot "installer\version.iss"

if (-not $SkipBuild) {
    & "$PSScriptRoot\build.ps1" -SkipInstaller
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

if (-not (Test-Path $exePath)) {
    Write-Host "Build output not found: $exePath" -ForegroundColor Red
    Write-Host "Run first: .\build.ps1 -SkipInstaller" -ForegroundColor Yellow
    exit 1
}

@"
; Generated by build_installer.ps1 from version.py
#define AppVersion "$version"
"@ | Set-Content -Path $versionIssPath -Encoding UTF8

$iscc = Get-InnoSetupCompiler
Write-Host "Building Inno Setup installer..." -ForegroundColor Cyan
& $iscc (Join-Path $PSScriptRoot "installer\ChatList.iss")

if ($LASTEXITCODE -ne 0) {
    Write-Host "Inno Setup build failed" -ForegroundColor Red
    exit $LASTEXITCODE
}

if (-not (Test-Path $installerPath)) {
    Write-Host "Installer not created: $installerPath" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Installer ready: $installerPath" -ForegroundColor Green
Write-Host "Version: $version" -ForegroundColor Green
